import { Marcellus } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/navigater/Sidebar";
import Navigatebar from "./component/navigater/Navigatebar";

const marcellus = Marcellus({  weight: '400',
  subsets: ['latin'],});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={marcellus.className}>
     
        <Sidebar /><div style={{display:"flex",flexDirection:"column",width:"100%"}}><Navigatebar />{children}</div></body>
    </html>
  );
}
