import { Mulish } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/navigater/Sidebar";
import Navigatebar from "./component/navigater/Navigatebar";
import Navbar from "./component/navigater/Mobile/Navbar"
const mulish = Mulish({  weight: '400',
  subsets: ['latin'],});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
     
          <Sidebar />   {/* <Navigatebar /> */} {children}    <Navbar />  </body>
    </html>
  );
}
